export ZSH=$HOME/.dotfiles
export PROJECTS=~/dev

export PATH="./bin:/usr/local/bin:/usr/local/sbin:$ZSH/bin:$PATH"
export MANPATH="/usr/local/man:/usr/local/mysql/man:/usr/local/git/man:$MANPATH"

if [[ -a ~/.myzshrc ]]
then
      source ~/.myzshrc
fi
